# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Главное_окошко.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sqlite3

from PyQt5.QtGui import QFont


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1358, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 50, 291, 961))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.listWidget.setFont(font)

        # Подключение к существующей базе данных
        conn = sqlite3.connect('data/БД университетская библиотека.db')
        cursor = conn.cursor()

        query = "SELECT `Название_каталога` FROM `Каталоги`"
        cursor.execute(query)
        data_from_database = cursor.fetchall()
        conn.close()

        for item_data in data_from_database:
            item = QtWidgets.QListWidgetItem(item_data[0])
            self.listWidget.addItem(item)
            item.setSizeHint(QtCore.QSize(200, 50))

        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.itemClicked.connect(lambda item: self.show_books_for_directory(item.text()))
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 291, 41))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127)\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(1140, 10, 211, 1051))
        self.frame_2.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(60, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(40, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 170, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 230, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 290, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 10, 711, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setFont(QtGui.QFont("Arial", 12))
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1020, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(295, 51, 841, 651))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setColumnWidth(0, 100)  # Устанавливаем ширину первой колонки
        self.tableWidget.setColumnWidth(1, 200)
        self.tableWidget.setColumnWidth(2, 300)
        self.tableWidget.setColumnWidth(3, 150)
        self.tableWidget.setColumnWidth(4, 150)
        self.tableWidget.setColumnWidth(5, 150)
        self.tableWidget.setColumnWidth(6, 150)

        self.tableWidget.setHorizontalHeaderLabels(
            ["Код книги", "Название книги", "Аннотация","Автор", "Каталог", "Издательство", "Возрастное \n ограничение"])  #Заголовки столбцов
        # Подключение к существующей базе данных
        conn = sqlite3.connect('data/БД университетская библиотека.db')
        cursor = conn.cursor()

        # Выполнение запроса SELECT для получения данных из таблицы книги
        cursor.execute("SELECT * FROM Книги")
        books = cursor.fetchall()

        # Заполнение таблицы данными
        for row_number, row_data in enumerate(books):
            self.tableWidget.insertRow(row_number)
            font = QFont("Arial", 12)
            self.tableWidget.setFont(font)
            for column_number, data in enumerate(row_data):
                if column_number == 2:

                    text_edit = QtWidgets.QTextEdit(str(data))
                    text_edit.setReadOnly(True)
                    text_edit.setFrameStyle(QtWidgets.QFrame.NoFrame)
                    text_edit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                    self.tableWidget.setCellWidget(row_number, column_number, text_edit)
                else:
                    item = QtWidgets.QTableWidgetItem(str(data))
                    item.setFlags(item.flags() & ~QtCore.Qt.ItemIsEditable)  # Disable editing for other columns
                    self.tableWidget.setItem(row_number, column_number, item)

        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)  # Prevent column resizing
        self.tableWidget.resizeRowsToContents()

        # Закрытие подключения
        conn.close()

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Университетская библиотека"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Каталоги"))
        self.label_2.setText(_translate("MainWindow", "Настройки"))
        self.pushButton.setText(_translate("MainWindow", "Каталоги"))
        self.pushButton.clicked.connect(lambda: self.open_katalogi(MainWindow))
        self.pushButton_3.setText(_translate("MainWindow", "Читатели"))
        self.pushButton_3.clicked.connect(lambda: self.open_chitateli(MainWindow))
        self.pushButton_4.setText(_translate("MainWindow", "Книги"))
        self.pushButton_4.clicked.connect(lambda: self.open_knigi(MainWindow))
        self.pushButton_5.setText(_translate("MainWindow", "Учет выдачи"))
        self.pushButton_5.clicked.connect(lambda: self.open_uchet(MainWindow))
        self.pushButton_2.setText(_translate("MainWindow", "Поиск"))
        self.pushButton_2.clicked.connect(self.search_button_clicked)

    def show_books_for_directory(self, selected_directory):
        # Список выбранных книг в выбранном каталоге
        selected_dir_books = []

        # Подключение к базе данных
        conn = sqlite3.connect('data/БД университетская библиотека.db')
        cursor = conn.cursor()

        # Выполнение запроса SELECT для получения списка книг в выбранном каталоге
        query = "SELECT `Код_книги`, `Название_книги`, `Аннотация`, `Автор`, `Каталог`, `Издательство`, `Возрастное_ограничение` FROM `Книги` WHERE `Каталог` = ?"
        cursor.execute(query, (selected_directory,))
        selected_dir_books = cursor.fetchall()

        # Закрытие подключения к базе данных
        conn.close()

        # Очищаем таблицу перед отображением новых данных
        self.tableWidget.clearContents()
        self.tableWidget.setRowCount(0)

        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)  # Только для чтения
        font = QFont("Arial", 12)
        self.tableWidget.setFont(font)


        # Отображаем выбранные книги в таблице
        for book_data in selected_dir_books:
            book_kod = book_data[0]
            book_title = book_data[1]
            book_annot = book_data[2]
            book_author = book_data[3]
            book_katalog = book_data[4]
            book_publisher = book_data[5]
            book_vozrast_ogr = book_data[6]

            row_position = self.tableWidget.rowCount()
            self.tableWidget.insertRow(row_position)

            self.tableWidget.setItem(row_position, 0, QtWidgets.QTableWidgetItem(str(book_kod)))
            self.tableWidget.setItem(row_position, 1, QtWidgets.QTableWidgetItem(book_title))
            self.tableWidget.setItem(row_position, 2, QtWidgets.QTableWidgetItem(book_annot))
            self.tableWidget.setItem(row_position, 3, QtWidgets.QTableWidgetItem(book_author))
            self.tableWidget.setItem(row_position, 4, QtWidgets.QTableWidgetItem((book_katalog)))
            self.tableWidget.setItem(row_position, 5, QtWidgets.QTableWidgetItem(book_publisher))
            self.tableWidget.setItem(row_position, 6, QtWidgets.QTableWidgetItem(str(book_vozrast_ogr)))

            self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)  # Prevent column resizing
            self.tableWidget.resizeRowsToContents()


    def search_button_clicked(self):
        # Получение текста из строки поиска
        query = self.lineEdit.text()

        # Подключение к существующей базе данных
        conn = sqlite3.connect('data/БД университетская библиотека.db')
        cursor = conn.cursor()

        # Выполнение запроса SELECT для поиска по тексту
        search_query = f"SELECT * FROM Книги WHERE Код_книги LIKE '%{query}%' " \
                       f"OR Название_книги LIKE '%{query}%' " \
                       f"OR Аннотация LIKE '%{query}%' " \
                       f"OR Автор LIKE '%{query}%' " \
                       f"OR Издательство LIKE '%{query}%'"
        cursor.execute(search_query)
        search_results = cursor.fetchall()

        # Очистка таблицы перед выводом новых результатов
        self.tableWidget.clearContents()
        self.tableWidget.setRowCount(0)

        if len(search_results) == 0:
            QtWidgets.QMessageBox.information(
                self.centralwidget, "Результаты поиска", "По данному запросу ничего не найдено.")

        # Вывод результатов в таблицу
        for row_number, row_data in enumerate(search_results):
            self.tableWidget.insertRow(row_number)
            font = QtGui.QFont("Arial", 12)
            self.tableWidget.setFont(font)
            for column_number, data in enumerate(row_data):
                # Пропускаем ячейку с аннотацией
                if column_number == 2:

                    text_edit = QtWidgets.QTextEdit(str(data))
                    text_edit.setReadOnly(True)
                    text_edit.setFrameStyle(QtWidgets.QFrame.NoFrame)
                    text_edit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                    self.tableWidget.setCellWidget(row_number, column_number, text_edit)
                else:
                    item = QtWidgets.QTableWidgetItem(str(data))
                    item.setFlags(item.flags() & ~QtCore.Qt.ItemIsEditable)  # Disable editing for other columns
                    self.tableWidget.setItem(row_number, column_number, item)

            self.tableWidget.horizontalHeader().setSectionResizeMode(
                QtWidgets.QHeaderView.Fixed)  # Prevent column resizing
            self.tableWidget.resizeRowsToContents()

        # Закрытие подключения
        conn.close()

    def open_katalogi(self, MainWindow):
        self.window = QtWidgets.QMainWindow()
        self.ui = Spisok_katalogov()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.close()


    def open_chitateli(self, MainWindow):
        self.window = QtWidgets.QMainWindow()
        self.ui = Spisok_chitateley()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.close()

    def open_knigi(self, MainWindow):
        self.window = QtWidgets.QMainWindow()
        self.ui = Spisok_knig()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.close()

    def open_uchet(self, MainWindow):
        self.window = QtWidgets.QMainWindow()
        self.ui = Uchet()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.close()


class Spisok_katalogov(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1358, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1361, 91))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(620, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 90, 271, 611))
        self.frame_2.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(40, 60, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 120, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 178, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 240, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(270, 90, 1091, 611))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setColumnWidth(0, 370)  # Устанавливаем ширину первой колонки
        self.tableWidget.setColumnWidth(1, 685)
        self.tableWidget.setHorizontalHeaderLabels(
            ["Каталоги", "Описание каталога"])  # Заголовки столбцов
        font = QFont("Arial", 12)
        self.tableWidget.setFont(font)
        # Подключение к существующей базе данных
        conn = sqlite3.connect('data/БД университетская библиотека.db')
        cursor = conn.cursor()

        # Выполнение запроса SELECT для получения данных из таблицы книги
        cursor.execute("SELECT * FROM Каталоги")
        books = cursor.fetchall()

        for row_number, row_data in enumerate(books):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(data))
                item.setTextAlignment(QtCore.Qt.AlignVCenter)
                item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEnabled)
                item.setSizeHint(QtCore.QSize(100, 100))
                self.tableWidget.setItem(row_number, column_number, item)

        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)  # Prevent column resizing
        self.tableWidget.resizeRowsToContents()

        # Закрытие подключения
        conn.close()
        MainWindow.setCentralWidget(self.centralwidget)
        self.refresh_table()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def refresh_table(self):
        try:
            # Подключитесь к базе данных
            conn = sqlite3.connect('data/БД университетская библиотека.db')
            cursor = conn.cursor()

            # Выполните запрос на получение данных из таблицы Каталоги
            select_query = "SELECT * FROM Каталоги"
            cursor.execute(select_query)

            # Получите все строки результатов запроса
            rows = cursor.fetchall()

            # Очистите таблицу tablewidget
            self.tableWidget.clear()

            # Установите количество строк и столбцов в таблице tablewidget
            self.tableWidget.setRowCount(len(rows))
            self.tableWidget.setColumnCount(2)  # Предполагается, что в таблице есть 2 столбца
            self.tableWidget.setHorizontalHeaderLabels(
                ["Каталоги", "Описание каталога"])  # Заголовки столбцов
            font = QFont("Arial", 12)
            self.tableWidget.setFont(font)


            for i, row in enumerate(rows):
                for j, value in enumerate(row):
                    # Создайте элемент таблицы QTableWidgetItem с соответствующим значением
                    item = QtWidgets.QTableWidgetItem(str(value))
                    # Установите элемент в соответствующую ячейку таблицы
                    self.tableWidget.setItem(i, j, item)

                # Закройте соединение с базой данных
                conn.close()

        except sqlite3.Error as error:
            # Обработайте возможную ошибку при выполнении операций с базой данных
            print("Ошибка при выполнении операций с базой данных:", error)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Список каталогов"))
        self.label.setText(_translate("MainWindow", "Каталоги"))
        self.pushButton.setText(_translate("MainWindow", "Редактировать"))
        self.pushButton.clicked.connect(lambda: self.open_red_kataloga(MainWindow))
        self.pushButton_2.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_2.clicked.connect(lambda: self.open_dobavit_katalog(MainWindow))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_3.clicked.connect(self.delete_selected_row)
        self.pushButton_4.setText(_translate("MainWindow", "Назад"))
        self.pushButton_4.clicked.connect(lambda: self.nazad1(MainWindow))


    def open_red_kataloga(self, MainWindow):
        selected_row = self.tableWidget.currentRow()
        if selected_row >= 0:
            katalog = self.tableWidget.item(selected_row, 0).text()
            opisanie = self.tableWidget.item(selected_row, 1).text()

            self.window = QtWidgets.QDialog()
            self.ui = red_kataloga(katalog, opisanie, self.refresh_table, self.window)
            self.ui.setupUi(self.window)
            self.window.show()

    def open_dobavit_katalog(self, MainWindow):
        self.window = QtWidgets.QDialog()
        self.ui = okno_dobavit_katalog()
        self.ui.setupUi(self.window)
        self.window.show()

    def delete_selected_row(self):
        selected_row = self.tableWidget.currentRow()
        if selected_row >= 0:
            # Получение значения первой ячейки выбранной строки
            catalog_name = self.tableWidget.item(selected_row, 0).text()

            # Удаление строки из таблицы каталогов в базе данных
            conn = sqlite3.connect('data/БД университетская библиотека.db')
            cursor = conn.cursor()
            cursor.execute("DELETE FROM Каталоги WHERE Название_каталога = ?", (catalog_name,))
            conn.commit()
            conn.close()

            self.tableWidget.removeRow(selected_row)

    def nazad1(self, MainWindow):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.close()


class red_kataloga(object):

    def __init__(self, katalog, opisanie,refresh_table, Dialog):
        self.katalog = katalog
        self.opisanie = opisanie
        self.refresh_table = refresh_table
        self.Dialog = Dialog

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(479, 228)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(9, 9, 461, 211))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(110, 60, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(170, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 100, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Редактирование каталога"))
        self.label.setText(_translate("Dialog", "Редактирование"))
        self.lineEdit.setText(_translate("Dialog", "Название каталога"))
        self.pushButton.setText(_translate("Dialog", "Сохранить"))
        self.lineEdit_2.setText(_translate("Dialog", "Описание каталога"))
        self.lineEdit.setText(self.katalog)
        self.lineEdit_2.setText(self.opisanie)

        self.pushButton.clicked.connect(self.save_iz_kataloga)

    def save_iz_kataloga(self):
        # Получите данные из полей для ввода
        naz_kataloga = self.lineEdit.text()
        opisanie = self.lineEdit_2.text()
        # Сохраните данные в базу данных
        try:
            # Подключитесь к базе данных
            conn = sqlite3.connect('data/БД университетская библиотека.db')
            cursor = conn.cursor()
            print("Подключено")
            # Выполните запрос на удаление старой записи
            delete_query = "DELETE FROM Каталоги"
            cursor.execute(delete_query)
            print("Удалено")
            # Выполните запрос на вставку новой записи
            insert_query = "INSERT INTO Каталоги (Название_каталога, Описание_каталога) VALUES (?, ?)"
            cursor.execute(insert_query, (naz_kataloga, opisanie,))
            print("Вставлено")
            # Сохраните изменения в базе данных
            conn.commit()
            print("Сохранено")
            # Закройте соединение с базой данных
            conn.close()

            try:
                self.refresh_table()  # Здесь необходимо определить метод refresh_table() для обновления таблицы
                print("Обновлено")
                self.Dialog.accept()
                print("ЗАкрыто")
                # Обновите таблицу tablewidget
            except Exception as e:
                print("Ошибка при закрытии окна или обновлении таблицы:", e)

        except sqlite3.Error as error:
            # Обработайте возможную ошибку при выполнении операций с базой данных
            print("Ошибка при выполнении операций с базой данных:", error)

class okno_dobavit_katalog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(478, 228)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 461, 211))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(110, 60, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(170, 170, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 110, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Новый каталог"))
        self.label.setText(_translate("Dialog", "Новый каталог"))
        self.lineEdit.setText(_translate("Dialog", "Название каталога"))
        self.pushButton.setText(_translate("Dialog", "Создать"))
        self.lineEdit_2.setText(_translate("Dialog", "Описание каталога"))



class Spisok_chitateley(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1360, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1361, 91))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(620, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 90, 271, 611))
        self.frame_2.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(40, 60, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 120, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 178, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 240, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(270, 90, 1091, 611))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setColumnWidth(0, 150)  # Устанавливаем ширину первой колонки
        self.tableWidget.setColumnWidth(1, 450)
        self.tableWidget.setColumnWidth(2, 220)
        self.tableWidget.setColumnWidth(3, 250)
        self.tableWidget.setHorizontalHeaderLabels(
            ["№ читательского \n билета", "ФИО", "Дата рождения", "Номер телефона"])  # Заголовки столбцов

        font = QFont("Arial", 12)
        self.tableWidget.setFont(font)

        # Подключение к существующей базе данных
        conn = sqlite3.connect('data/БД университетская библиотека.db')
        cursor = conn.cursor()

        # Выполнение запроса SELECT для получения данных из таблицы книги
        cursor.execute("SELECT * FROM Читатели")
        books = cursor.fetchall()

        # Заполнение таблицы данными
        for row_number, row_data in enumerate(books):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(data))
                item.setTextAlignment(QtCore.Qt.AlignVCenter)
                item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEnabled)
                item.setSizeHint(QtCore.QSize(100, 100))
                self.tableWidget.setItem(row_number, column_number, item)

        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)
        self.tableWidget.resizeRowsToContents()

        # Закрытие подключения
        conn.close()

        MainWindow.setCentralWidget(self.centralwidget)
        self.refresh_table()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def refresh_table(self):
        try:
            # Подключитесь к базе данных
            conn = sqlite3.connect('data/БД университетская библиотека.db')
            cursor = conn.cursor()

            # Выполните запрос на получение данных из таблицы Каталоги
            select_query = "SELECT * FROM Читатели"
            cursor.execute(select_query)

            # Получите все строки результатов запроса
            rows = cursor.fetchall()

            # Очистите таблицу tablewidget
            self.tableWidget.clear()

            # Установите количество строк и столбцов в таблице tablewidget
            self.tableWidget.setRowCount(len(rows))
            self.tableWidget.setColumnCount(4)  # Предполагается, что в таблице есть 4 столбца
            self.tableWidget.setHorizontalHeaderLabels(
                ["№читательского \n билета", "ФИО", "Дата рождения", "Номер телефона"])  # Заголовки столбцов
            font = QFont("Arial", 12)
            self.tableWidget.setFont(font)

            for i, row in enumerate(rows):
                for j, value in enumerate(row):
                    # Создайте элемент таблицы QTableWidgetItem с соответствующим значением
                    item = QtWidgets.QTableWidgetItem(str(value))
                    # Установите элемент в соответствующую ячейку таблицы
                    self.tableWidget.setItem(i, j, item)

                # Закройте соединение с базой данных
                conn.close()

        except sqlite3.Error as error:
            # Обработайте возможную ошибку при выполнении операций с базой данных
            print("Ошибка при выполнении операций с базой данных:", error)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Список читателей"))
        self.label.setText(_translate("MainWindow", "Читатели"))
        self.pushButton.setText(_translate("MainWindow", "Редактировать"))
        self.pushButton.clicked.connect(lambda: self.open_red_chitatela(MainWindow))
        self.pushButton_2.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_2.clicked.connect(lambda: self.open_dobavit_chitatela(MainWindow))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_3.clicked.connect(self.delete_selected_row)
        self.pushButton_4.setText(_translate("MainWindow", "Назад"))
        self.pushButton_4.clicked.connect(lambda: self.nazad2(MainWindow))

    def open_red_chitatela(self, MainWindow):
        selected_row = self.tableWidget.currentRow()
        if selected_row >= 0:
            chit_bilet = self.tableWidget.item(selected_row, 0).text()  # №читательского_билета
            fio = self.tableWidget.item(selected_row, 1).text()  # Изменение столбца на второй (1) - ФИО
            data_rojdenia = self.tableWidget.item(selected_row, 2).text()
            nomer_telefona = self.tableWidget.item(selected_row, 3).text()

            self.window = QtWidgets.QDialog()
            self.ui = red_chitatela(chit_bilet, fio, data_rojdenia, nomer_telefona, self.refresh_table, self.window)
            self.ui.setupUi(self.window)
            self.window.show()

    def open_dobavit_chitatela(self, MainWindow):
        self.window = QtWidgets.QDialog()
        self.ui = dobavit_chitatela()
        self.ui.setupUi(self.window)
        self.window.show()

    def delete_selected_row(self):
        selected_row = self.tableWidget.currentRow()
        if selected_row >= 0:
            # Получение значения первой ячейки выбранной строки
            chitatel = self.tableWidget.item(selected_row, 0).text()

            # Удаление строки из таблицы каталогов в базе данных
            conn = sqlite3.connect('data/БД университетская библиотека.db')
            cursor = conn.cursor()
            cursor.execute("DELETE FROM Читатели WHERE №читательского_билета = ?", (chitatel,))
            conn.commit()
            conn.close()

            self.tableWidget.removeRow(selected_row)

    def nazad2(self, MainWindow):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.close()

class red_chitatela(object):
    def __init__(self, fio, data_rojdenia, chit_bilet, nomer_telefona, refresh_table, Dialog):
        self.fio = fio
        self.data_rojdenia = data_rojdenia
        self.chit_bilet = chit_bilet
        self.nomer_telefona = nomer_telefona
        self.refresh_table = refresh_table
        self.Dialog = Dialog

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(531, 379)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(9, 9, 511, 361))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(120, 80, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 130, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 180, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 230, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(200, 290, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Редактирование читателя"))
        self.label.setText(_translate("Dialog", "Редактирование"))
        self.lineEdit.setText(_translate("Dialog", "ФИО"))
        self.lineEdit_2.setText(_translate("Dialog", "Дата рождения"))
        self.lineEdit_3.setText(_translate("Dialog", "№ читательского билета"))
        self.lineEdit_4.setText(_translate("Dialog", "Номер телефона"))
        self.pushButton.setText(_translate("Dialog", "Сохранить"))
        self.pushButton.clicked.connect(self.save_iz_chitatela)

    def save_iz_chitatela(self):
        fio = self.lineEdit.text()
        data_rojdenia = self.lineEdit_2.text()
        chit_bilet = self.lineEdit_3.text()
        nomer_telefona = self.lineEdit_4.text()

        try:
            conn = sqlite3.connect('data/БД университетская библиотека.db')
            cursor = conn.cursor()

            update_query = "UPDATE Читатели SET ФИО=?, Дата_рождения=?, Номер_телефона=? WHERE №читательского_билета=?"  # Исправлен запрос
            cursor.execute(update_query, (fio, data_rojdenia, nomer_telefona, chit_bilet))

            conn.commit()
            conn.close()

            try:
                self.refresh_table()
                self.Dialog.accept()
            except Exception as e:
                print("Ошибка при закрытии окна или обновлении таблицы:", e)

        except sqlite3.Error as error:
            print("Ошибка при выполнении операций с базой данных:", error)

class dobavit_chitatela(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(533, 377)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 511, 361))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(120, 80, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 130, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 180, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 230, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(200, 290, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Новый читатель"))
        self.label.setText(_translate("Dialog", "Новый читатель"))
        self.lineEdit.setText(_translate("Dialog", "ФИО"))
        self.lineEdit_2.setText(_translate("Dialog", "Дата рождения"))
        self.lineEdit_3.setText(_translate("Dialog", "№ читательского билета"))
        self.lineEdit_4.setText(_translate("Dialog", "Номер телефона"))
        self.pushButton.setText(_translate("Dialog", "Создать"))
        self.pushButton.clicked.connect(self.save_chitatela)

    def save_chitatela(self):
        # Получите данные из полей для ввода
        chitatel_fio = self.lineEdit.text()
        chitatel_data_rojdenia = self.lineEdit_2.text()
        chitatel_chit_bilet = self.lineEdit_3.text()
        chitatel_phone = self.lineEdit_4.text()

        # Сохраните данные в базу данных
        try:
            # Подключитесь к базе данных
            conn = sqlite3.connect('data/БД университетская библиотека.db')
            cursor = conn.cursor()

            # Выполните запрос на вставку новой записи
            insert_query = "INSERT INTO Читатели (ФИО, Дата_рождения, №читательского_билета, Номер_телефона) VALUES (?, ?, ?, ?)"
            cursor.execute(insert_query, (chitatel_fio, str(chitatel_data_rojdenia), str(chitatel_chit_bilet), str(chitatel_phone)))

            # Сохраните изменения в базе данных
            conn.commit()

            # Закройте соединение с базой данных
            conn.close()

        except sqlite3.Error as error:
            # Обработайте возможную ошибку при выполнении операций с базой данных
            print("Ошибка при выполнении операций с базой данных:", error)

class Spisok_knig(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1360, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1361, 91))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(660, 20, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 90, 271, 611))
        self.frame_2.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(40, 60, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 120, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 178, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 240, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(270, 90, 1091, 611))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setColumnWidth(1, 200)
        self.tableWidget.setColumnWidth(2, 300)
        self.tableWidget.setColumnWidth(3, 150)
        self.tableWidget.setColumnWidth(4, 150)
        self.tableWidget.setColumnWidth(5, 150)
        self.tableWidget.setColumnWidth(6, 150)
        self.tableWidget.setHorizontalHeaderLabels(
            ["Код книги", "Название книги", "Аннотация", "Автор", "Каталог", "Издательство",
             "Возрастное \n ограничение"])  # Заголовки столбцов

        font = QFont("Arial", 12)
        self.tableWidget.setFont(font)

        # Подключение к существующей базе данных
        conn = sqlite3.connect('data/БД университетская библиотека.db')
        cursor = conn.cursor()

        # Выполнение запроса SELECT для получения данных из таблицы книги
        cursor.execute("SELECT * FROM Книги")
        books = cursor.fetchall()

        # Заполнение таблицы данными
        for row_number, row_data in enumerate(books):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                if column_number == 2:

                    text_edit = QtWidgets.QTextEdit(str(data))
                    text_edit.setReadOnly(True)
                    text_edit.setFrameStyle(QtWidgets.QFrame.NoFrame)
                    text_edit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                    self.tableWidget.setCellWidget(row_number, column_number, text_edit)

                else:
                    item = QtWidgets.QTableWidgetItem(str(data))
                    item.setFlags(item.flags() & ~QtCore.Qt.ItemIsEditable)  # Disable editing for other columns
                    self.tableWidget.setItem(row_number, column_number, item)

        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)  # Prevent column resizing
        self.tableWidget.resizeRowsToContents()
        # Закрытие подключения
        conn.close()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Список_книг"))
        self.label.setText(_translate("MainWindow", "Книги"))
        self.pushButton.setText(_translate("MainWindow", "Редактировать"))
        self.pushButton.clicked.connect(lambda: self.open_red_knigi(MainWindow))
        self.pushButton_2.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_2.clicked.connect(lambda: self.open_dobavit_knigy(MainWindow))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_3.clicked.connect(self.delete_selected_row)
        self.pushButton_4.setText(_translate("MainWindow", "Назад"))
        self.pushButton_4.clicked.connect(lambda: self.nazad3(MainWindow))

    def open_red_knigi(self, MainWindow):
        # Получение выбранной строки
        selected_row = self.tableWidget.currentRow()
        if selected_row >= 0:
            # Получение данных из выбранной строки
            kod_knigi = self.tableWidget.item(selected_row, 0).text()
            nazvanie = self.tableWidget.item(selected_row, 1).text()
            annotaciya = self.tableWidget.cellWidget(selected_row, 2).toPlainText()
            avtor = self.tableWidget.item(selected_row, 3).text()
            katalog = self.tableWidget.item(selected_row, 4).text()
            izdatelstvo = self.tableWidget.item(selected_row, 5).text()
            vozrastnoe_ogranichenie = self.tableWidget.item(selected_row, 6).text()
            self.window = QtWidgets.QDialog()
            self.ui = red_knigi()
            self.ui.setupUi(self.window)

            # Заполнение полей окна редактирования данными из выбранной строки
            self.ui.lineEdit.setText(kod_knigi)
            self.ui.lineEdit_2.setText(nazvanie)
            self.ui.lineEdit_3.setText(avtor)
            self.ui.lineEdit_4.setText(izdatelstvo)
            self.ui.lineEdit_5.setText(vozrastnoe_ogranichenie)
            self.ui.lineEdit_6.setText(katalog)
            self.ui.lineEdit_7.setText(annotaciya)
            self.window.show()


    def open_dobavit_knigy(self, MainWindow):
        self.window = QtWidgets.QDialog()
        self.ui = dobavit_knigy()
        self.ui.setupUi(self.window)
        self.window.show()

    def delete_selected_row(self):
        selected_row = self.tableWidget.currentRow()
        if selected_row >= 0:
            # Получение значения первой ячейки выбранной строки
            kniga = self.tableWidget.item(selected_row, 0).text()

            # Удаление строки из таблицы каталогов в базе данных
            conn = sqlite3.connect('data/БД университетская библиотека.db')
            cursor = conn.cursor()
            cursor.execute("DELETE FROM Книги WHERE Код_книги = ?", (kniga,))
            conn.commit()
            conn.close()

            self.tableWidget.removeRow(selected_row)


    def nazad3(self, MainWindow):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.close()

class red_knigi(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 379)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(9, 9, 511, 361))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(10, 70, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 70, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 120, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(270, 120, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 170, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(270, 170, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 220, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(190, 300, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Редактирование_книги"))
        self.label.setText(_translate("Dialog", "Редактирование"))
        self.lineEdit.setText(_translate("Dialog", "Код книги"))
        self.lineEdit_2.setText(_translate("Dialog", "Название"))
        self.lineEdit_3.setText(_translate("Dialog", "Автора"))
        self.lineEdit_4.setText(_translate("Dialog", "Издательство"))
        self.lineEdit_5.setText(_translate("Dialog", "Возрастное ограничение"))
        self.lineEdit_6.setText(_translate("Dialog", "Каталог"))
        self.lineEdit_7.setText(_translate("Dialog", "Аннотация"))
        self.pushButton.setText(_translate("Dialog", "Сохранить"))
        self.pushButton.clicked.connect(self.save_iz_kigi)

    def save_iz_kigi(self):
        # Получите данные из полей для ввода
        kod_knigi = self.lineEdit.text()
        naz = self.lineEdit_2.text()
        avtor = self.lineEdit_3.text()
        izdatelstvo = self.lineEdit_4.text()
        vozras_ogran = self.lineEdit_5.text()
        katalog = self.lineEdit_6.text()
        annotasia = self.lineEdit_7.text()

        # Сохраните данные в базу данных
        try:
            # Подключитесь к базе данных
            conn = sqlite3.connect('data/БД университетская библиотека.db')
            cursor = conn.cursor()


            # Удалите старую запись, если она существует
            delete_query = "DELETE FROM Книги WHERE Код_книги = ?"
            cursor.execute(delete_query, (kod_knigi,))

            # Выполните запрос на вставку новой записи
            insert_query = "INSERT INTO Книги (Код_книги, Название_книги, Автор, Издательство, Возрастное_ограничение, Каталог, Аннотация) VALUES (?, ?, ?, ?, ?, ?, ?)"
            cursor.execute(insert_query,
                           (kod_knigi, naz, avtor, izdatelstvo, vozras_ogran,
                            katalog, annotasia))

            # Сохраните изменения в базе данных
            conn.commit()

            # Закройте соединение с базой данных
            conn.close()

        except sqlite3.Error as error:
            # Обработайте возможную ошибку при выполнении операций с базой данных
            print("Ошибка при выполнении операций с базой данных:", error)

class dobavit_knigy(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 377)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 511, 361))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(190, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(10, 70, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 70, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 120, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(270, 120, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 170, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(270, 170, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 220, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(190, 300, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Новая книга"))
        self.label.setText(_translate("Dialog", "Новая книги"))
        self.lineEdit.setText(_translate("Dialog", "Код книги"))
        self.lineEdit_2.setText(_translate("Dialog", "Название книги"))
        self.lineEdit_3.setText(_translate("Dialog", "Автор"))
        self.lineEdit_4.setText(_translate("Dialog", "Издательство"))
        self.lineEdit_5.setText(_translate("Dialog", "Возрастное ограничение"))
        self.lineEdit_6.setText(_translate("Dialog", "Каталог"))
        self.lineEdit_7.setText(_translate("Dialog", "Аннотация"))
        self.pushButton.setText(_translate("Dialog", "Создать"))

class Uchet(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1367, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1371, 81))
        self.frame.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(600, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(159, 109, 1081, 561))
        self.frame_2.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(105, 61, 871, 461))
        self.tableWidget.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setColumnWidth(0, 350)
        self.tableWidget.setColumnWidth(1, 350)
        self.tableWidget.setColumnWidth(2, 185)

        self.tableWidget.setHorizontalHeaderLabels(
            ["Читатель", "Книга", "Дата сдачи"])  # Заголовки столбцов

        # Подключение к существующей базе данных
        conn = sqlite3.connect('data/БД университетская библиотека.db')
        cursor = conn.cursor()

        # Выполнение запроса SELECT для получения данных из таблицы книги
        cursor.execute("SELECT Читатели.ФИО AS Читатель, Книги.Название_книги AS Название_книги, Оформление_книги.Дата_сдачи AS Дата_сдачи "
                       "FROM Оформление_книги "
                       "JOIN Книги ON Оформление_книги.Название_книги = Книги.Код_книги "
                       "JOIN Читатели ON Оформление_книги.№читательского_билета = Читатели.№читательского_билета")
        books = cursor.fetchall()

        # Заполнение таблицы данными
        for row_number, row_data in enumerate(books):
            self.tableWidget.insertRow(row_number)

            for column_number, data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(data))
                item.setTextAlignment(QtCore.Qt.AlignVCenter)
                item.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEnabled)
                item_font = QtGui.QFont()
                item_font.setPointSize(12)
                item.setFont(item_font)
                item.setSizeHint(QtCore.QSize(100, 100))
                self.tableWidget.setItem(row_number, column_number, item)

        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)
        self.tableWidget.resizeRowsToContents()

        # Закрытие подключения
        conn.close()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Учет выдачи"))
        self.label.setText(_translate("MainWindow", "Учет выдачи"))
        self.pushButton_3.setText(_translate("MainWindow", "Назад"))
        self.pushButton_3.clicked.connect(lambda: self.nazad4(MainWindow))

    def nazad4(self, MainWindow):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())