# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Список_читателей.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReaderListWindow(object):
    def setupUi(self, ReaderListWindow):
        ReaderListWindow.setObjectName("ReaderListWindow")
        ReaderListWindow.resize(906, 551)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReaderListWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(ReaderListWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(450, 30, 131, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(13, 89, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(ReaderListWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(260, 0))
        self.frame_2.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_edit = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_edit.setGeometry(QtCore.QRect(40, 60, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_edit.setFont(font)
        self.pushButton_edit.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 71, 41);")
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.pushButton_app = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_app.setGeometry(QtCore.QRect(40, 120, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_app.setFont(font)
        self.pushButton_app.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 71, 41);")
        self.pushButton_app.setObjectName("pushButton_app")
        self.pushButton_del = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_del.setGeometry(QtCore.QRect(40, 178, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_del.setFont(font)
        self.pushButton_del.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 71, 41);")
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_back = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_back.setGeometry(QtCore.QRect(40, 240, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: rgb(0, 37, 255);")
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.tableWidget = QtWidgets.QTableWidget(ReaderListWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ReaderListWindow)
        QtCore.QMetaObject.connectSlotsByName(ReaderListWindow)

    def retranslateUi(self, ReaderListWindow):
        _translate = QtCore.QCoreApplication.translate
        ReaderListWindow.setWindowTitle(_translate("ReaderListWindow", "Библиотека: Список каталогов"))
        self.label.setText(_translate("ReaderListWindow", "Читатели"))
        self.pushButton_edit.setText(_translate("ReaderListWindow", "Редактировать"))
        self.pushButton_app.setText(_translate("ReaderListWindow", "Добавить"))
        self.pushButton_del.setText(_translate("ReaderListWindow", "Удалить"))
        self.pushButton_back.setText(_translate("ReaderListWindow", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReaderListWindow = QtWidgets.QWidget()
    ui = Ui_ReaderListWindow()
    ui.setupUi(ReaderListWindow)
    ReaderListWindow.show()
    sys.exit(app.exec_())
