# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Книга.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewWindow(object):
    def setupUi(self, ViewWindow):
        ViewWindow.setObjectName("ViewWindow")
        ViewWindow.resize(635, 496)
        ViewWindow.setStyleSheet("background-color:rgb(170, 255, 127);\n"
"color: rgb(0, 26, 255);")
        self.frame = QtWidgets.QFrame(ViewWindow)
        self.frame.setGeometry(QtCore.QRect(9, 9, 611, 481))
        self.frame.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(280, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_book = QtWidgets.QLabel(self.frame)
        self.label_book.setGeometry(QtCore.QRect(26, 52, 561, 361))
        self.label_book.setStyleSheet("background-color: rgb(171, 255, 128);")
        self.label_book.setWordWrap(True)
        self.label_book.setObjectName("label_book")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(230, 420, 181, 41))
        self.pushButton.setStyleSheet("color: rgb(255, 16, 0);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ViewWindow)
        QtCore.QMetaObject.connectSlotsByName(ViewWindow)

    def retranslateUi(self, ViewWindow):
        _translate = QtCore.QCoreApplication.translate
        ViewWindow.setWindowTitle(_translate("ViewWindow", "Книга"))
        self.label.setText(_translate("ViewWindow", "Книга"))
        self.label_book.setText(_translate("ViewWindow", "TextLabel"))
        self.pushButton.setText(_translate("ViewWindow", "Оформить книгу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewWindow = QtWidgets.QDialog()
    ui = Ui_ViewWindow()
    ui.setupUi(ViewWindow)
    ViewWindow.show()
    sys.exit(app.exec_())
