# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Новый_каталог.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewCat(object):
    def setupUi(self, NewCat):
        NewCat.setObjectName("NewCat")
        NewCat.resize(478, 228)
        self.frame = QtWidgets.QFrame(NewCat)
        self.frame.setGeometry(QtCore.QRect(10, 10, 461, 211))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127);\n"
"color: rgb(6, 48, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.katalog = QtWidgets.QLineEdit(self.frame)
        self.katalog.setGeometry(QtCore.QRect(110, 60, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.katalog.setFont(font)
        self.katalog.setObjectName("katalog")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(170, 170, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.opisanie = QtWidgets.QLineEdit(self.frame)
        self.opisanie.setGeometry(QtCore.QRect(110, 110, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.opisanie.setFont(font)
        self.opisanie.setObjectName("opisanie")

        self.retranslateUi(NewCat)
        QtCore.QMetaObject.connectSlotsByName(NewCat)

    def retranslateUi(self, NewCat):
        _translate = QtCore.QCoreApplication.translate
        NewCat.setWindowTitle(_translate("NewCat", "Новый каталог"))
        self.label.setText(_translate("NewCat", "Новый каталог"))
        self.katalog.setText(_translate("NewCat", "Название каталога"))
        self.pushButton.setText(_translate("NewCat", "Создать"))
        self.opisanie.setText(_translate("NewCat", "Описание каталога"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewCat = QtWidgets.QDialog()
    ui = Ui_NewCat()
    ui.setupUi(NewCat)
    NewCat.show()
    sys.exit(app.exec_())
