# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Оформление.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrepareWindow(object):
    def setupUi(self, PrepareWindow):
        PrepareWindow.setObjectName("PrepareWindow")
        PrepareWindow.resize(529, 380)
        self.frame = QtWidgets.QFrame(PrepareWindow)
        self.frame.setGeometry(QtCore.QRect(9, 9, 511, 361))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127);\n"
"color: rgb(255, 0, 29);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 10, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_name = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_name.setGeometry(QtCore.QRect(170, 110, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setReadOnly(True)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_number = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_number.setGeometry(QtCore.QRect(170, 160, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_number.setFont(font)
        self.lineEdit_number.setObjectName("lineEdit_number")
        self.lineEdit_date0 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_date0.setGeometry(QtCore.QRect(170, 210, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_date0.setFont(font)
        self.lineEdit_date0.setObjectName("lineEdit_date0")
        self.lineEdit_date1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_date1.setGeometry(QtCore.QRect(170, 260, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_date1.setFont(font)
        self.lineEdit_date1.setObjectName("lineEdit_date1")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(170, 310, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_code = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_code.setGeometry(QtCore.QRect(170, 60, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_code.setFont(font)
        self.lineEdit_code.setReadOnly(True)
        self.lineEdit_code.setObjectName("lineEdit_code")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 91, 16))
        self.label_2.setStyleSheet("color: rgb(22, 65, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 121, 20))
        self.label_3.setStyleSheet("color: rgb(22, 65, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(60, 170, 91, 16))
        self.label_4.setStyleSheet("color: rgb(22, 65, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 131, 20))
        self.label_5.setStyleSheet("color: rgb(22, 65, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(60, 270, 91, 16))
        self.label_6.setStyleSheet("color: rgb(22, 65, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(PrepareWindow)
        QtCore.QMetaObject.connectSlotsByName(PrepareWindow)

    def retranslateUi(self, PrepareWindow):
        _translate = QtCore.QCoreApplication.translate
        PrepareWindow.setWindowTitle(_translate("PrepareWindow", "Оформление книги"))
        self.label.setText(_translate("PrepareWindow", "Оформление книги"))
        self.lineEdit_name.setText(_translate("PrepareWindow", "Название книги"))
        self.lineEdit_number.setText(_translate("PrepareWindow", "№ читательского билета"))
        self.lineEdit_date0.setText(_translate("PrepareWindow", "Дата оформления"))
        self.lineEdit_date1.setText(_translate("PrepareWindow", "Дата сдачи"))
        self.pushButton.setText(_translate("PrepareWindow", "Оформить книгу"))
        self.lineEdit_code.setText(_translate("PrepareWindow", "Код книги"))
        self.label_2.setText(_translate("PrepareWindow", "Код книги:"))
        self.label_3.setText(_translate("PrepareWindow", "Наименование:"))
        self.label_4.setText(_translate("PrepareWindow", "№ чит.билета:"))
        self.label_5.setText(_translate("PrepareWindow", "Дата оформления:"))
        self.label_6.setText(_translate("PrepareWindow", "Дата сдачи:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PrepareWindow = QtWidgets.QDialog()
    ui = Ui_PrepareWindow()
    ui.setupUi(PrepareWindow)
    PrepareWindow.show()
    sys.exit(app.exec_())
