# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Редактирование_читателя.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditChitWindow(object):
    def setupUi(self, EditChitWindow):
        EditChitWindow.setObjectName("EditChitWindow")
        EditChitWindow.resize(531, 379)
        self.frame = QtWidgets.QFrame(EditChitWindow)
        self.frame.setGeometry(QtCore.QRect(10, 10, 511, 361))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127);\n"
"color: rgb(1, 36, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_fio = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_fio.setGeometry(QtCore.QRect(120, 80, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_fio.setFont(font)
        self.lineEdit_fio.setText("")
        self.lineEdit_fio.setObjectName("lineEdit_fio")
        self.lineEdit_born = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_born.setGeometry(QtCore.QRect(120, 130, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_born.setFont(font)
        self.lineEdit_born.setText("")
        self.lineEdit_born.setObjectName("lineEdit_born")
        self.lineEdit_number = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_number.setGeometry(QtCore.QRect(120, 180, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_number.setFont(font)
        self.lineEdit_number.setText("")
        self.lineEdit_number.setObjectName("lineEdit_number")
        self.lineEdit_phone = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_phone.setGeometry(QtCore.QRect(120, 230, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_phone.setFont(font)
        self.lineEdit_phone.setText("")
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(200, 290, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 58, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 61, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 180, 61, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 230, 58, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(EditChitWindow)
        QtCore.QMetaObject.connectSlotsByName(EditChitWindow)

    def retranslateUi(self, EditChitWindow):
        _translate = QtCore.QCoreApplication.translate
        EditChitWindow.setWindowTitle(_translate("EditChitWindow", "Редактирование читателя"))
        self.label.setText(_translate("EditChitWindow", "Читатель библиотеки"))
        self.pushButton.setText(_translate("EditChitWindow", "Сохранить"))
        self.label_2.setText(_translate("EditChitWindow", "ФИО"))
        self.label_3.setText(_translate("EditChitWindow", "Дата \n"
"рождения"))
        self.label_4.setText(_translate("EditChitWindow", "№ чит.\n"
"билета"))
        self.label_5.setText(_translate("EditChitWindow", "Телефон"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditChitWindow = QtWidgets.QDialog()
    ui = Ui_EditChitWindow()
    ui.setupUi(EditChitWindow)
    EditChitWindow.show()
    sys.exit(app.exec_())
