# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Редактирование_каталога.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemCatEdit(object):
    def setupUi(self, ItemCatEdit):
        ItemCatEdit.setObjectName("ItemCatEdit")
        ItemCatEdit.resize(479, 228)
        ItemCatEdit.setStyleSheet("")
        self.frame = QtWidgets.QFrame(ItemCatEdit)
        self.frame.setGeometry(QtCore.QRect(9, 9, 461, 211))
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127);\n"
"color: rgb(16, 0, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.katalog = QtWidgets.QLineEdit(self.frame)
        self.katalog.setGeometry(QtCore.QRect(110, 60, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.katalog.setFont(font)
        self.katalog.setObjectName("katalog")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(170, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.opisanie = QtWidgets.QLineEdit(self.frame)
        self.opisanie.setGeometry(QtCore.QRect(110, 100, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.opisanie.setFont(font)
        self.opisanie.setObjectName("opisanie")

        self.retranslateUi(ItemCatEdit)
        QtCore.QMetaObject.connectSlotsByName(ItemCatEdit)

    def retranslateUi(self, ItemCatEdit):
        _translate = QtCore.QCoreApplication.translate
        ItemCatEdit.setWindowTitle(_translate("ItemCatEdit", "Редактирование каталога"))
        self.label.setText(_translate("ItemCatEdit", "Редактирование"))
        self.katalog.setText(_translate("ItemCatEdit", "Название каталога"))
        self.pushButton.setText(_translate("ItemCatEdit", "Сохранить"))
        self.opisanie.setText(_translate("ItemCatEdit", "Описание каталога"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ItemCatEdit = QtWidgets.QDialog()
    ui = Ui_ItemCatEdit()
    ui.setupUi(ItemCatEdit)
    ItemCatEdit.show()
    sys.exit(app.exec_())
