# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Учет.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UchetWindow(object):
    def setupUi(self, UchetWindow):
        UchetWindow.setObjectName("UchetWindow")
        UchetWindow.resize(789, 632)
        self.verticalLayout = QtWidgets.QVBoxLayout(UchetWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(UchetWindow)
        self.frame.setMinimumSize(QtCore.QSize(0, 80))
        self.frame.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.frame.setStyleSheet("background-color:rgb(170, 255, 127);\n"
"color: rgb(7, 0, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(310, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_back = QtWidgets.QPushButton(self.frame)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton_back.setObjectName("pushButton_back")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(UchetWindow)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setStyleSheet("background-color: rgb(170, 255, 131);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.tableWidget = QtWidgets.QTableWidget(UchetWindow)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.label_3 = QtWidgets.QLabel(UchetWindow)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setStyleSheet("background-color: rgb(170, 255, 131);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(UchetWindow)
        QtCore.QMetaObject.connectSlotsByName(UchetWindow)

    def retranslateUi(self, UchetWindow):
        _translate = QtCore.QCoreApplication.translate
        UchetWindow.setWindowTitle(_translate("UchetWindow", "Form"))
        self.label.setText(_translate("UchetWindow", "Учет выдачи"))
        self.pushButton_back.setText(_translate("UchetWindow", "Назад"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("UchetWindow", "Новая строка"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("UchetWindow", "Новая строка"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("UchetWindow", "Новый столбец"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("UchetWindow", "Новый столбец"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UchetWindow = QtWidgets.QWidget()
    ui = Ui_UchetWindow()
    ui.setupUi(UchetWindow)
    UchetWindow.show()
    sys.exit(app.exec_())
